version: '3'
services:
  pnr_status_app:
    container_name: pnr_status_app_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
    restart: always
